// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/main.proto

package main_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorUpdateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	TempF string `protobuf:"bytes,2,opt,name=tempF,proto3" json:"tempF,omitempty"`
	TempC string `protobuf:"bytes,3,opt,name=tempC,proto3" json:"tempC,omitempty"`
	HighF string `protobuf:"bytes,4,opt,name=highF,proto3" json:"highF,omitempty"`
	HighC string `protobuf:"bytes,5,opt,name=highC,proto3" json:"highC,omitempty"`
	LowF  string `protobuf:"bytes,6,opt,name=lowF,proto3" json:"lowF,omitempty"`
	LowC  string `protobuf:"bytes,7,opt,name=lowC,proto3" json:"lowC,omitempty"`
	Time  string `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SensorUpdateDto) Reset() {
	*x = SensorUpdateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorUpdateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorUpdateDto) ProtoMessage() {}

func (x *SensorUpdateDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorUpdateDto.ProtoReflect.Descriptor instead.
func (*SensorUpdateDto) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{0}
}

func (x *SensorUpdateDto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SensorUpdateDto) GetTempF() string {
	if x != nil {
		return x.TempF
	}
	return ""
}

func (x *SensorUpdateDto) GetTempC() string {
	if x != nil {
		return x.TempC
	}
	return ""
}

func (x *SensorUpdateDto) GetHighF() string {
	if x != nil {
		return x.HighF
	}
	return ""
}

func (x *SensorUpdateDto) GetHighC() string {
	if x != nil {
		return x.HighC
	}
	return ""
}

func (x *SensorUpdateDto) GetLowF() string {
	if x != nil {
		return x.LowF
	}
	return ""
}

func (x *SensorUpdateDto) GetLowC() string {
	if x != nil {
		return x.LowC
	}
	return ""
}

func (x *SensorUpdateDto) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_proto_main_proto protoreflect.FileDescriptor

var file_proto_main_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xbb, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x6d, 0x70, 0x46, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x65, 0x6d, 0x70, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x6d, 0x70,
	0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x6d, 0x70, 0x43, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x69, 0x67, 0x68, 0x46, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68,
	0x69, 0x67, 0x68, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x69, 0x67, 0x68, 0x43, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x69, 0x67, 0x68, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x77, 0x46, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x77, 0x46, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x6f, 0x77, 0x43, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f,
	0x77, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_main_proto_rawDescOnce sync.Once
	file_proto_main_proto_rawDescData = file_proto_main_proto_rawDesc
)

func file_proto_main_proto_rawDescGZIP() []byte {
	file_proto_main_proto_rawDescOnce.Do(func() {
		file_proto_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_main_proto_rawDescData)
	})
	return file_proto_main_proto_rawDescData
}

var file_proto_main_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_main_proto_goTypes = []interface{}{
	(*SensorUpdateDto)(nil), // 0: main.SensorUpdateDto
}
var file_proto_main_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_main_proto_init() }
func file_proto_main_proto_init() {
	if File_proto_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorUpdateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_main_proto_goTypes,
		DependencyIndexes: file_proto_main_proto_depIdxs,
		MessageInfos:      file_proto_main_proto_msgTypes,
	}.Build()
	File_proto_main_proto = out.File
	file_proto_main_proto_rawDesc = nil
	file_proto_main_proto_goTypes = nil
	file_proto_main_proto_depIdxs = nil
}
